// This file was automatically generated by drizzle-zero.
// You should NOT make any changes in this file as it will be overwritten.

import type { ReadonlyJSONValue, Row } from "@rocicorp/zero";
import { createBuilder } from "@rocicorp/zero";
import type { CustomType } from "drizzle-zero";
import type * as drizzleSchema from "./db/schema.js";

const accountTable = {
  name: "account",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    email: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    name: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    createdAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
  },
  primaryKey: ["id"],
} as const;
const auditLogTable = {
  name: "auditLog",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    entityType: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "entity_type",
    },
    entityId: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "entity_id",
    },
    action: {
      type: "string",
      optional: false,
      customType: null as unknown as
        | "insert"
        | "create"
        | "update"
        | "upsert"
        | "delete",
    },
    actorType: {
      type: "string",
      optional: false,
      customType: null as unknown as "user" | "worker" | "system",
      serverName: "actor_type",
    },
    actorId: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "actor_id",
    },
    metadata: {
      type: "json",
      optional: true,
      customType: null as unknown as ReadonlyJSONValue,
    },
    createdAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "created_at",
    },
  },
  primaryKey: ["id"],
  serverName: "audit_log",
} as const;
const channelDependenciesTable = {
  name: "channelDependencies",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    channelId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "channel_id",
    },
    dependencyPackageId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "dependency_package_id",
    },
    dependencyVersionRange: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "dependency_version_range",
    },
    dependencyType: {
      type: "string",
      optional: false,
      customType: null as unknown as "runtime" | "dev" | "peer" | "optional",
      serverName: "dependency_type",
    },
    createdAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "created_at",
    },
  },
  primaryKey: ["id"],
  serverName: "channel_dependencies",
} as const;
const packageFetchesTable = {
  name: "packageFetches",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    packageId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "package_id",
    },
    status: {
      type: "string",
      optional: false,
      customType: null as unknown as "failed" | "pending" | "completed",
    },
    errorMessage: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "error_message",
    },
    createdAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    completedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "completed_at",
    },
  },
  primaryKey: ["id"],
  serverName: "package_fetches",
} as const;
const packageReleaseChannelsTable = {
  name: "packageReleaseChannels",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    packageId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "package_id",
    },
    channel: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    version: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    publishedAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "published_at",
    },
    createdAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
  },
  primaryKey: ["id"],
  serverName: "package_release_channels",
} as const;
const packageTagsTable = {
  name: "packageTags",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    packageId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "package_id",
    },
    tagId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "tag_id",
    },
    createdAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "created_at",
    },
  },
  primaryKey: ["id"],
  serverName: "package_tags",
} as const;
const packageUpvotesTable = {
  name: "packageUpvotes",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    packageId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "package_id",
    },
    accountId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "account_id",
    },
    createdAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "created_at",
    },
  },
  primaryKey: ["id"],
  serverName: "package_upvotes",
} as const;
const packagesTable = {
  name: "packages",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    name: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    registry: {
      type: "string",
      optional: false,
      customType: null as unknown as "npm",
    },
    status: {
      type: "string",
      optional: false,
      customType: null as unknown as "active" | "failed" | "placeholder",
    },
    failureReason: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "failure_reason",
    },
    description: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    homepage: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    repository: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    latestVersion: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "latest_version",
    },
    distTags: {
      type: "json",
      optional: true,
      customType: null as unknown as CustomType<
        typeof drizzleSchema,
        "packages",
        "distTags"
      >,
      serverName: "dist_tags",
    },
    upvoteCount: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "upvote_count",
    },
    lastFetchAttempt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "last_fetch_attempt",
    },
    lastFetchSuccess: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "last_fetch_success",
    },
    createdAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
  },
  primaryKey: ["id"],
} as const;
const projectPackagesTable = {
  name: "projectPackages",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    projectId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "project_id",
    },
    packageId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "package_id",
    },
    createdAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "created_at",
    },
  },
  primaryKey: ["id"],
  serverName: "project_packages",
} as const;
const projectsTable = {
  name: "projects",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    name: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    description: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    accountId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "account_id",
    },
    createdAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
  },
  primaryKey: ["id"],
} as const;
const tagsTable = {
  name: "tags",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    name: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    slug: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    description: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    createdAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
  },
  primaryKey: ["id"],
} as const;
const accountRelationships = {
  projects: [
    {
      sourceField: ["id"],
      destField: ["accountId"],
      destSchema: "projects",
      cardinality: "many",
    },
  ],
  upvotes: [
    {
      sourceField: ["id"],
      destField: ["accountId"],
      destSchema: "packageUpvotes",
      cardinality: "many",
    },
  ],
} as const;
const auditLogRelationships = {
  actor: [
    {
      sourceField: ["actorId"],
      destField: ["id"],
      destSchema: "account",
      cardinality: "one",
    },
  ],
} as const;
const channelDependenciesRelationships = {
  channel: [
    {
      sourceField: ["channelId"],
      destField: ["id"],
      destSchema: "packageReleaseChannels",
      cardinality: "one",
    },
  ],
  dependencyPackage: [
    {
      sourceField: ["dependencyPackageId"],
      destField: ["id"],
      destSchema: "packages",
      cardinality: "one",
    },
  ],
} as const;
const packageFetchesRelationships = {
  package: [
    {
      sourceField: ["packageId"],
      destField: ["id"],
      destSchema: "packages",
      cardinality: "one",
    },
  ],
} as const;
const packageReleaseChannelsRelationships = {
  package: [
    {
      sourceField: ["packageId"],
      destField: ["id"],
      destSchema: "packages",
      cardinality: "one",
    },
  ],
  dependencies: [
    {
      sourceField: ["id"],
      destField: ["channelId"],
      destSchema: "channelDependencies",
      cardinality: "many",
    },
  ],
} as const;
const packageTagsRelationships = {
  package: [
    {
      sourceField: ["packageId"],
      destField: ["id"],
      destSchema: "packages",
      cardinality: "one",
    },
  ],
  tag: [
    {
      sourceField: ["tagId"],
      destField: ["id"],
      destSchema: "tags",
      cardinality: "one",
    },
  ],
} as const;
const packageUpvotesRelationships = {
  package: [
    {
      sourceField: ["packageId"],
      destField: ["id"],
      destSchema: "packages",
      cardinality: "one",
    },
  ],
  account: [
    {
      sourceField: ["accountId"],
      destField: ["id"],
      destSchema: "account",
      cardinality: "one",
    },
  ],
} as const;
const packagesRelationships = {
  releaseChannels: [
    {
      sourceField: ["id"],
      destField: ["packageId"],
      destSchema: "packageReleaseChannels",
      cardinality: "many",
    },
  ],
  channelDependents: [
    {
      sourceField: ["id"],
      destField: ["dependencyPackageId"],
      destSchema: "channelDependencies",
      cardinality: "many",
    },
  ],
  packageTags: [
    {
      sourceField: ["id"],
      destField: ["packageId"],
      destSchema: "packageTags",
      cardinality: "many",
    },
  ],
  fetches: [
    {
      sourceField: ["id"],
      destField: ["packageId"],
      destSchema: "packageFetches",
      cardinality: "many",
    },
  ],
  upvotes: [
    {
      sourceField: ["id"],
      destField: ["packageId"],
      destSchema: "packageUpvotes",
      cardinality: "many",
    },
  ],
  projectPackages: [
    {
      sourceField: ["id"],
      destField: ["packageId"],
      destSchema: "projectPackages",
      cardinality: "many",
    },
  ],
} as const;
const projectPackagesRelationships = {
  project: [
    {
      sourceField: ["projectId"],
      destField: ["id"],
      destSchema: "projects",
      cardinality: "one",
    },
  ],
  package: [
    {
      sourceField: ["packageId"],
      destField: ["id"],
      destSchema: "packages",
      cardinality: "one",
    },
  ],
} as const;
const projectsRelationships = {
  account: [
    {
      sourceField: ["accountId"],
      destField: ["id"],
      destSchema: "account",
      cardinality: "one",
    },
  ],
  projectPackages: [
    {
      sourceField: ["id"],
      destField: ["projectId"],
      destSchema: "projectPackages",
      cardinality: "many",
    },
  ],
} as const;
const tagsRelationships = {
  packageTags: [
    {
      sourceField: ["id"],
      destField: ["tagId"],
      destSchema: "packageTags",
      cardinality: "many",
    },
  ],
} as const;
/**
 * The Zero schema object.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const schema = {
  tables: {
    account: accountTable,
    auditLog: auditLogTable,
    channelDependencies: channelDependenciesTable,
    packageFetches: packageFetchesTable,
    packageReleaseChannels: packageReleaseChannelsTable,
    packageTags: packageTagsTable,
    packageUpvotes: packageUpvotesTable,
    packages: packagesTable,
    projectPackages: projectPackagesTable,
    projects: projectsTable,
    tags: tagsTable,
  },
  relationships: {
    account: accountRelationships,
    auditLog: auditLogRelationships,
    channelDependencies: channelDependenciesRelationships,
    packageFetches: packageFetchesRelationships,
    packageReleaseChannels: packageReleaseChannelsRelationships,
    packageTags: packageTagsRelationships,
    packageUpvotes: packageUpvotesRelationships,
    packages: packagesRelationships,
    projectPackages: projectPackagesRelationships,
    projects: projectsRelationships,
    tags: tagsRelationships,
  },
  enableLegacyQueries: false,
  enableLegacyMutators: false,
} as const;

/**
 * Represents the Zero schema type.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Schema = typeof schema;
/**
 * Represents a row from the "account" table.
 * This type is auto-generated from your Drizzle schema definition.
 *
 * @deprecated Use Row["account"] instead from "@rocicorp/zero".
 */
export type Account = Row["account"];
/**
 * Represents a row from the "auditLog" table.
 * This type is auto-generated from your Drizzle schema definition.
 *
 * @deprecated Use Row["auditLog"] instead from "@rocicorp/zero".
 */
export type AuditLog = Row["auditLog"];
/**
 * Represents a row from the "channelDependencies" table.
 * This type is auto-generated from your Drizzle schema definition.
 *
 * @deprecated Use Row["channelDependencies"] instead from "@rocicorp/zero".
 */
export type ChannelDependency = Row["channelDependencies"];
/**
 * Represents a row from the "packageFetches" table.
 * This type is auto-generated from your Drizzle schema definition.
 *
 * @deprecated Use Row["packageFetches"] instead from "@rocicorp/zero".
 */
export type PackageFetch = Row["packageFetches"];
/**
 * Represents a row from the "packageReleaseChannels" table.
 * This type is auto-generated from your Drizzle schema definition.
 *
 * @deprecated Use Row["packageReleaseChannels"] instead from "@rocicorp/zero".
 */
export type PackageReleaseChannel = Row["packageReleaseChannels"];
/**
 * Represents a row from the "packageTags" table.
 * This type is auto-generated from your Drizzle schema definition.
 *
 * @deprecated Use Row["packageTags"] instead from "@rocicorp/zero".
 */
export type PackageTag = Row["packageTags"];
/**
 * Represents a row from the "packageUpvotes" table.
 * This type is auto-generated from your Drizzle schema definition.
 *
 * @deprecated Use Row["packageUpvotes"] instead from "@rocicorp/zero".
 */
export type PackageUpvote = Row["packageUpvotes"];
/**
 * Represents a row from the "packages" table.
 * This type is auto-generated from your Drizzle schema definition.
 *
 * @deprecated Use Row["packages"] instead from "@rocicorp/zero".
 */
export type Package = Row["packages"];
/**
 * Represents a row from the "projectPackages" table.
 * This type is auto-generated from your Drizzle schema definition.
 *
 * @deprecated Use Row["projectPackages"] instead from "@rocicorp/zero".
 */
export type ProjectPackage = Row["projectPackages"];
/**
 * Represents a row from the "projects" table.
 * This type is auto-generated from your Drizzle schema definition.
 *
 * @deprecated Use Row["projects"] instead from "@rocicorp/zero".
 */
export type Project = Row["projects"];
/**
 * Represents a row from the "tags" table.
 * This type is auto-generated from your Drizzle schema definition.
 *
 * @deprecated Use Row["tags"] instead from "@rocicorp/zero".
 */
export type Tag = Row["tags"];

/**
 * Represents the ZQL query builder.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const zql = createBuilder(schema);
/**
 * Represents the Zero schema query builder.
 * This type is auto-generated from your Drizzle schema definition.
 *
 * @deprecated Use `zql` instead.
 */
export const builder = zql;

/** Defines the default types for Zero */
declare module "@rocicorp/zero" {
  interface DefaultTypes {
    schema: Schema;
  }
}
